# -*- coding: utf-8 -*-
"""
Created on Wed Dec  5 21:12:17 2018

@author: Feng-cong Li
"""

from ctypes.wintypes import BYTE, WORD



BATTERY_DEVTYPE_GAMEPAD = BYTE(0)
BATTERY_DEVTYPE_HEADSET = BYTE(1)

BATTERY_LEVEL_EMPTY     = BYTE(0)
BATTERY_LEVEL_FULL      = BYTE(3)
BATTERY_LEVEL_LOW       = BYTE(1)
BATTERY_LEVEL_MEDIUM    = BYTE(2)

BATTERY_TYPE_ALKALINE       = BYTE(2)
BATTERY_TYPE_DISCONNECTED   = BYTE(0)
BATTERY_TYPE_NIMH           = BYTE(3)
BATTERY_TYPE_UNKNOWN        = BYTE(0XFF)
BATTERY_TYPE_WIRED          = BYTE(1)

XINPUT_GAMEPAD_DPAD_UP          = WORD(0x0001)
XINPUT_GAMEPAD_DPAD_DOWN        = WORD(0x0002)
XINPUT_GAMEPAD_DPAD_LEFT        = WORD(0x0004)
XINPUT_GAMEPAD_DPAD_RIGHT       = WORD(0x0008)
XINPUT_GAMEPAD_START            = WORD(0x0010)
XINPUT_GAMEPAD_BACK             = WORD(0x0020)
XINPUT_GAMEPAD_LEFT_THUMB       = WORD(0x0040)
XINPUT_GAMEPAD_RIGHT_THUMB      = WORD(0x0080)
XINPUT_GAMEPAD_LEFT_SHOULDER    = WORD(0x0100)
XINPUT_GAMEPAD_RIGHT_SHOULDER   = WORD(0x0200)
XINPUT_GAMEPAD_A = WORD(0x1000)
XINPUT_GAMEPAD_B = WORD(0x2000)
XINPUT_GAMEPAD_X = WORD(0x4000)
XINPUT_GAMEPAD_Y = WORD(0x8000)