#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Fri May 23 10:56:05 2014

@author: Feng-cong Li
"""
import platform
from wavesynlib import application

if __name__ == '__main__':
    # On Windows platform, spawn.py of Multiprocessing always try to access
    # the "__spec__" property of "__main__", and it seems that the wrapper 
    # script generated by setuptools will fail to provide this property. 
    if platform.system() == 'Windows':
        __spec__ = None 
    application.mainloop()
